 posts_info ='{"posts":[{\
"post_id":"static0",\
"post_creation_ts":"-1",\
"post_description":"HelloFriends,...",\
"post_hashtags":[\
"whitehouse",\
"usa"\
],\
"post_content_path":"db/posts/content/static0.jpeg",\
"author_username":"obama",\
"author_avatar_path":"db/posts/content/static0.jpeg"\
},\
{\
"post_id":"static1",\
"post_creation_ts":"-1",\
"post_description":"HelloFriends,...",\
"post_hashtags":[\
"whitehouse"\
],\
"post_content_path":"db/posts/content/static1.jpeg",\
"author_username":"obama.president",\
"author_avatar_path":"db/posts/content/static1.jpeg"\
},\
{\
"post_id":"static2",\
"post_creation_ts":"-1",\
"post_description":"HelloFriends,...",\
"post_hashtags":[\
"hello",\
"fridayswithobama"\
],\
"post_content_path":"db/posts/content/static2.jpeg",\
"author_username":"obama",\
"author_avatar_path":"db/posts/content/static0.jpeg"\
},\
{\
"post_id":"static3",\
"post_creation_ts":"-1",\
"post_description":"HelloFriends,...",\
"post_hashtags":[\
],\
"post_content_path":"db/posts/content/static3.jpeg",\
"author_username":"obama_whitehouse",\
"author_avatar_path":"db/posts/content/static3.jpeg"\
}]}';